// Canonical API shapes — keep in sync with FastAPI response schemas.
// Import from here; never declare Session/Asset/Group/etc. inline.

export type SessionStatus = "pending" | "syncing" | "ready" | "error" | "deleted";
export type AssetStatus = "active" | "rejected";
export type UserDecision = "pending" | "accepted" | "rejected" | "manual";
export type FaceCropStatus = "cropped" | "uploaded" | "blended";
export type CostKind = "free" | "paid" | "ai";
export type CloudProvider = "google_drive" | "mega";

// ── Sessions ──────────────────────────────────────────────────────────────────

export interface Session {
  id: string;
  cloudFolderName: string;
  cloudFolderId: string;
  cloudProvider: CloudProvider;
  assetCount: number;
  groupCount: number;
  status: SessionStatus;
  costToDateUsd: number;
  createdAt: string;
  updatedAt: string;
  thumbnailAssetIds: string[];
}

export interface SessionDetail extends Session {
  groups: Group[];
  ungroupedAssetIds: string[];
}

// ── Assets ────────────────────────────────────────────────────────────────────

export interface Asset {
  id: string;
  sessionId: string;
  originalFilename: string;
  originalCloudPath: string;
  thumbnailUrl: string;
  previewUrl: string;
  isVideo: boolean;
  hasFace: boolean;
  aestheticScore: number | null;
  phash: string | null;
  nearDuplicateClusterId: string | null;
  takenAt: string | null;
  gpsLat: number | null;
  gpsLng: number | null;
  status: AssetStatus;
  currentEditVersionId: string | null;
  exifJson: Record<string, unknown> | null;
}

// ── Groups ────────────────────────────────────────────────────────────────────

export interface Group {
  id: string;
  sessionId: string;
  name: string;
  autoGenerated: boolean;
  orderIndex: number;
  assets: Asset[];
}

// ── Edits ─────────────────────────────────────────────────────────────────────

export interface EditVersion {
  id: string;
  assetId: string;
  parentVersionId: string | null;
  createdAt: string;
  correctionsAppliedJson: Record<string, unknown>;
  changesLogText: string;
  outputPath: string | null;
  previewUrl: string;
  userDecision: UserDecision;
}

export interface EditCandidatesResponse {
  proposals: EditVersion[];
  current: EditVersion;
}

// ── Face crops ────────────────────────────────────────────────────────────────

export interface FaceBbox {
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface FaceCrop {
  id: string;
  assetId: string;
  bboxJson: FaceBbox;
  cropUrl: string;
  uploadedCropUrl: string | null;
  blendedOutputUrl: string | null;
  status: FaceCropStatus;
}

// ── Descriptions ──────────────────────────────────────────────────────────────

export interface Description {
  id: string;
  groupId: string;
  text: string;
  customPrompt: string | null;
  modelUsed: string;
  tokensUsed: number;
  createdAt: string;
}

// ── Cost ──────────────────────────────────────────────────────────────────────

export interface CostEstimate {
  operation: string;
  estimatedDollars: number;
  estimatedTokens: number | null;
  sessionTotalDollars: number;
  budgetDollars: number;
  remainingDollars: number;
  hardCapDollars: number;
  exceedsSoftCap: boolean;
  exceedsHardCap: boolean;
}

export interface CostLogEntry {
  id: string;
  sessionId: string;
  operation: string;
  model: string | null;
  tokens: number;
  dollarsEstimate: number;
  createdAt: string;
}

export interface CostSummary {
  totalDollars: number;
  budgetDollars: number;
  hardCapDollars: number;
  byOperation: Array<{
    operation: string;
    count: number;
    model: string | null;
    tokens: number;
    dollars: number;
  }>;
}

// ── Storage / Drive ───────────────────────────────────────────────────────────

export interface DriveStatus {
  connected: boolean;
  email?: string;
}

export interface DriveFolderPreview {
  id: string;
  name: string;
  fileCount: number;
  sampleThumbnails: string[];
  approxBytes: number;
}

// ── Auth / Settings ───────────────────────────────────────────────────────────

export interface AuthMe {
  email: string;
  createdAt: string;
}

export interface Settings {
  claudeApiKey: string | null;
  replicateApiKey: string | null;
  googleClientId: string | null;
  googleClientSecret: string | null;
  sessionBudgetUsd: number;
  sessionHardCapUsd: number;
  styleSeed: string | null;
}

export interface SettingsPatch {
  claudeApiKey?: string | null;
  replicateApiKey?: string | null;
  googleClientId?: string | null;
  googleClientSecret?: string | null;
  sessionBudgetUsd?: number | null;
  sessionHardCapUsd?: number | null;
  styleSeed?: string | null;
}

// ── Grouping ──────────────────────────────────────────────────────────────────

export interface ReorderAssetsBody {
  assetIds: string[];
}

export interface MoveAssetBody {
  targetGroupId: string;
  position: number;
}
